GPIB_AVR: debugshell.c File Reference
debugshell.c File Reference
#include "string.h"
#include <avr/io.h>
#include <avr/pgmspace.h>
#include "gpib.h"
#include "uart.h"
#include "debugshell.h"
Functions
void debugshell (void)
Debug shell function.
Function Documentation
void debugshell (void)
Debug shell function.
this function is called if timeout situations occur in the code. The debugshell allows to manually check the state of the lines. If they are allowed to be changed manually, this should be implemented here too.
References buf, buf_ptr, gpib_info(), UART_BUFFER_OVERFLOW, UART_FRAME_ERROR, uart_getc(), UART_NO_DATA, UART_OVERRUN_ERROR, uart_putc(), uart_puts(), and uart_puts_P.
Referenced by _gpib_write(), gpib_receive(), and main().